//Nesse arquivo serve para criar tipoes de ações para ser utilizadas.

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_REQUEST = "UPDATE_REQUEST";
export const UPDATE_FAILURE = "UPDATE_FAILURE";

export const ADD_CARRINHO_SUCCESS = "ADD_CARRINHO_SUCCESS";
export const ADD_CARRINHO_REQUEST = "ADD_CARRINHO_REQUEST";
export const ADD_CARRINHO_FAILURE = "ADD_CARRINHO_FAILURE";

export const REMOVE_PRODUTO_SUCCESS = "REMOVE_PRODUTO_SUCCESS";
export const REMOVE_PRODUTO_REQUEST = "REMOVE_PRODUTO_REQUEST";
export const REMOVE_PRODUTO_FAILURE = "REMOVE_PRODUTO_FAILURE";

export const PERSIST_REHYDRATE = "persist/REHYDRATE";